name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        run: |
          git config --global url."https://${{secrets.ACCESS_TOKEN}}:@github.com/".insteadOf "https://github.com/"
          git clone https://github.com/tonradar/ton-dice-web-contract.git
        
      - name: Build the Docker image
        run: |
          cd $GITHUB_REPOSITORY
          docker build . --file Dockerfile --tag $GITHUB_REPOSITORY:$GITHUB_SHA --build-arg GITHUB_TOKEN=${{secrets.ACCESS_TOKEN}}
